name: Run PyAutoGUI Bot + Docker Parallel

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '2,17,32,47 * * * *'

jobs:
  run-pyautogui:
    name: Run PyAutoGUI (Windows)
    runs-on: windows-latest
    timeout-minutes: 13
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      fail-fast: false

    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: ▶️ Run bot script (PyAutoGUI)
        run: python main.py
      - name: ▶️ Run bot script 2 (PyAutoGUI)
        run: python main.py

  run-docker:
    name: Run Docker Containers (Ubuntu)
    runs-on: ubuntu-latest
    needs: run-pyautogui    # ✅ Chỉ chạy sau khi job Windows chạy xong
    timeout-minutes: 15
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      fail-fast: false

    steps:
      - name: 🐳 Set up Docker
        uses: docker/setup-buildx-action@v3
    
      - name: 🐳 Pull Docker Images
        run: |
          docker pull nduythanh1/selenium-videozz-multiprocess:latest
          docker pull nduythanh1/selenium-earnvids-app2:latest
    
      - name: ▶️ Run 4 Docker Containers in Parallel
        run: |
          # 2 containers từ selenium-videozz-multiprocess
          docker run -d --name svmp1 -e JOB_ID=${{ matrix.job_id }} nduythanh1/selenium-videozz-multiprocess:latest
          docker run -d --name svmp2 -e JOB_ID=${{ matrix.job_id }} nduythanh1/selenium-videozz-multiprocess:latest
    
          # 2 containers từ selenium-earnvids-app2
          docker run -d --name seapp2-1 -e JOB_ID=${{ matrix.job_id }} nduythanh1/selenium-earnvids-app2:latest
          docker run -d --name seapp2-2 -e JOB_ID=${{ matrix.job_id }} nduythanh1/selenium-earnvids-app2:latest
    
          # Chờ tất cả 4 container kết thúc song song
          docker wait svmp1 svmp2 seapp2-1 seapp2-2
